const fontFamily = {
  Montserrat_Regular: 'Montserrat-Regular',
  Montserrat_Bold: 'Montserrat-Bold',
  Calibri_Bold: 'Calibri-Bold',
  Calibri_Regular: 'Calibri',
  Calibri_Italic: 'Calibri-Italic',
  Montserrat_SemiBold: 'Montserrat-SemiBold',
  Proxima_Regular: 'Proxima-Regular',
  Proxima_Bold: 'Proxima-Bold',
  Proxima_SemiBold: 'Proxima-SemiBold',
  Nunito_Regular: 'Nunito-Regular',
  Nunito_Bold: 'Nunito-Bold',
  Nunito_SemiBold: 'Nunito_SemiBold',
  SignPainter_Regular: 'SignPainter-Regular',
  SignPainter_SemiBold: 'SignPainter-SemiBold',
  SF_Bold: 'SF-Bold',
  SF_SemiBold: 'SF-SemiBold',
  SF_Regular: 'SF-Regular',
  OpenSans_Bold: 'OpenSans-Bold',
  OpenSans_Regular: 'OpenSans-Regular',
  OpenSans_SemiBold: 'OpenSans-Semibold',
  KaushanScript_Regular: 'KaushanScript-Regular',
  Touche_Bold: 'Touche-Bold',
  Touche_Regular: 'Touche-Regular',
  Touche_SemiBold: 'Touche-Semibold',
  Baskerville_Old_Face: 'Baskerville-Old-Face',
};

export {fontFamily};
